### PR TITLE
Optimization: Cache calculated NodeId in the NodeRecord

### PR DESCRIPTION
**Pull request by Nashatyrev**
## PR Description

`NodeId` calculation takes a lot of time and need to be cached 

изображение

### CODE REVIEW

**Review by tbenr — APPROVED** [review]
LGTM

**Comment by ajsutton** [comment]
I think this is definitely good, I wonder if its worth also having a separate publicKey->nodeId cache (probably with some extra details around ensuring the same identity scheme is used etc).  There are a lot of node records we get from `NODES` messages which we parse and have to calculate the nodeId to validate they're from the requested distance. My guess is that a lot of these we've seen before and could just use the cached node ID even though it will be a new instance of `NodeRecord`.

**Comment by ajsutton** [comment]
Going to merge this one as-is because it's such a quick easy win.  A separate cache of calculated node IDs is probably worth looking into as a follow up when time permits though.

**Comment by Nashatyrev** [comment]
After this PR the signature verification is the major bottleneck (see flame graph below)  So it probably makes more sense to cache validated records (by their RLP hash?) assuming we are probably receiving many duplicates. 
(`NodeId` calculation takes roughly 5% of overall discovery CPU at the moment )

изображение

**Comment by Nashatyrev** [comment]
We could actually combine both approaches into a single cache: 
```java
LRUMap<PublicKey, CacheEntry> nodeCache

class CacheEntry {
    final Bytes nodeId;
    Optional<Bytes32> lastVerifiedRLPHash;
}
```
I believe we could afford keeping up to 10K entries in that cache (would be roughly around 1Mb of heap at most)

**Pull request merged**
