### PR TITLE
Increase the number of packets allowed per message

### PR DESCRIPTION
**Pull request by rolfyone**
A lot of messages were being discarded because of the packet restriction, which limits the nodes we have in our tables, so increasing this should help with finding nodes.

partially addresses #103

Signed-off-by: Paul Harris <paul.harris@consensys.net>

### CODE REVIEW

**Comment by SangameswaranRS** [comment]
Should the MAX_NODES_PER_MESSAGE = 4 and total =16 be changed also in FindNodeHandler ?

This change only handles the client side. As we have restricted nodes in node bucket(k=16), this change might help  only if we are querying for multiple buckets in List of distances that can be provided with a FIND_NODES request.

Please correct me if I'm wrong.

**Comment by rolfyone** [comment]
> Should the MAX_NODES_PER_MESSAGE = 4 and total =16 be changed also in FindNodeHandler ?
> 
> This change only handles the client side. As we have restricted nodes in node bucket(k=16), this change might help only if we are querying for multiple buckets in List of distances that can be provided with a FIND_NODES request.
> 
> Please correct me if I'm wrong.

I was querying against an eth2 bootnode and was running up against this limit when the node would attempt to send back up to 9 packets in a message, so I guess ultimately I was acting as a client in this instance...

It appears that the limit is an arbitrary one and not set by the spec, but I could definitely be wrong, I've read the spec over but am still coming up to speed, i'd definitely be interested in any insights that anyone may have...

The issue I was investigating is why teku bootnodes don't seem to have a lot of peers, and this code basically drops all responses with more than 5 packets, meaning we never import the responses into our tables, if that adds any context...

**Comment by SangameswaranRS** [comment]
@rolfyone , thanks for the explanation,
Basically what NODES packet we receive is sent from the Handler in pipeline, as the handler itself was restricted to 4 Max packets, Im confused so as how would we receive > 4 packets. 

Are the constraints different for an ETH boot node?
Just curious. Please correct if Im wrong.
Perhaps the authors can give a better explanation. @ajsutton

**Comment by rolfyone** [comment]
I'm still putting it all together... I'm finding it hard to get any kind of commitment on limits in the spec, all I know is i was reading from a bootnode and was getting a lot of messages containing 9 packets, and they get dumped because they're more than what was deemed valid. I'll keep digging.

**Comment by ajsutton** [comment]
I'm not the original author of this code - I just happened to be the one that imported it into git. 

I believe the original 5 packet response is because previously you could only request one distance per request and given the maximum size of an ENR, the maximum of 16 nodes per k-bucket and the maximum size of packets, you should be able to fit any response into 4 packets and 5 gives a little wiggle room.  However the spec now allows requesting multiple distances at once which may require more packets to return.

We want some limit in there so that we don't have to keep processing responses forever but the limit of what we choose to receive doesn't have to be the same as what we choose to send.  It looks like the EF bootnodes (using the go implementation) don't pack ENRs into packets as well as they could so wind up sending more packets than we would for the same response.

**Comment by ajsutton** [comment]
And yes, it may also make sense to review the limit we place on the number of records we send in responses bu that's a separate issue.  It's probably good to keep that fairly small since it's a case where a small request generates a larger response - the requester has to go through the handshake process so it shouldn't be an amplification attack risk, but we still don't want to let the imbalance be too great or it becomes a DOS vector.

**Review by ajsutton — APPROVED** [review]

**Pull request merged**
